name: Deploy application

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment for images to be pushed.
        required: true
        type: string
        default: production-test
      argocd_workload_repository:
        description: Argocd workload repository name in form - org-name/repo-name.
        required: true
        type: string
        default: githb-experiments/test-workload
  push:
    branches:
       - main
       - develop
       - test
  workflow_call:
    inputs:
      environment:
        description: Environment for images to be pushed.
        required: true
        type: string
        default: production-test
      argocd_workload_repository:
        description: Argocd workload repository name in form - org-name/repo-name.
        required: true
        type: string
        default: githb-experiments/test-workload

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Start Test Deployment
        run: echo "Starting test deployment"

  checkout-workload-repo:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: Echo input repo
      run: |
        echo Starting test checkout
        echo ${{ inputs.argocd_workload_repository }}
    - name: Show Folders initial
      run: ls -al
    - name: Checkout ArgoCD repository
      uses: actions/checkout@v4
      with:
        repository: githb-experiments/test-workload
        ssh-key: ${{ secrets.deploy_key }}
    - name: Show Folders final
      run: ls -al
